Potree.Shaders["pointcloud.fs"] = [
 "",
 "precision mediump float;",
 "precision mediump int;",
 "",
 "#if defined use_interpolation",
 "	#extension GL_EXT_frag_depth : enable",
 "#endif",
 "",
 "uniform mat4 viewMatrix;",
 "uniform vec3 cameraPosition;",
 "",
 "",
 "uniform mat4 projectionMatrix;",
 "uniform float opacity;",
 "",
 "uniform float blendHardness;",
 "uniform float blendDepthSupplement;",
 "uniform float fov;",
 "uniform float spacing;",
 "uniform float near;",
 "uniform float far;",
 "uniform float pcIndex;",
 "uniform float screenWidth;",
 "uniform float screenHeight;",
 "",
 "uniform sampler2D depthMap;",
 "",
 "varying vec3	vColor;",
 "varying vec3	vViewPosition;",
 "",
 THREE.ShaderChunk[ "common" ],
 "float specularStrength = 1.0;",
 "",
 "void main() {",
 "  vec3 outgoingLight = vec3( 0.0 );",
 "",
 "	vec3 color = vColor;",
 "	float depth = gl_FragCoord.z;",
 "",
 "	",

 "	",
 "		",
 "		vec4 pos = vec4(vViewPosition, 1.0);",
 "		float startOpacity = 1.0-(-pos.z-7.0)/7.0;",
 "		gl_FragColor = vec4(color*startOpacity, 1.0);",
 "	}",
].join("\n");
