Potree.Shaders["pointcloud.fs"] = [
 "",
 "precision mediump float;",
 "precision mediump int;",
 "",
 "#if defined use_interpolation",
 "	#extension GL_EXT_frag_depth : enable",
 "#endif",
 "",
 "uniform mat4 viewMatrix;",
 "uniform vec3 cameraPosition;",
 "",
 "",
 "uniform mat4 projectionMatrix;",
 "uniform float opacity;",
 "",
 "uniform float blendHardness;",
 "uniform float blendDepthSupplement;",
 "uniform float fov;",
 "uniform float spacing;",
 "uniform float near;",
 "uniform float far;",
 "uniform float pcIndex;",
 "uniform float screenWidth;",
 "uniform float screenHeight;",
 "",
 "uniform sampler2D depthMap;",
 "",
 "varying vec3	vColor;",
 "varying vec3	vViewPosition;",
 "",
 THREE.ShaderChunk[ "common" ],
 "float specularStrength = 1.0;",
 "",
 "void main() {",
 "  vec3 outgoingLight = vec3( 0.0 );",
 "",
 "	vec3 color = vColor;",
 "	float depth = gl_FragCoord.z;",
 "",
 "		vec4 pos = vec4(vViewPosition, 1.0);",
 "      float startOpacity = 1.0;",
 //threshold is 10.0. Points closer to Z = -10 won't have gradient.
 //9.5 is the gradient range. -> From -10.0 to -19.5.
 "      startOpacity = 1.0-(-pos.z)/19.5;",
 "		startOpacity = max(0.0, startOpacity);",
 "		gl_FragColor = vec4(vec3(1.0)*startOpacity, 1.0);",
 "	}",
].join("\n");
